# Generated by Django 2.2.6 on 2019-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('nationality', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('view', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('roomnumber', models.IntegerField()),
                ('ammenities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('adults', models.IntegerField()),
                ('kids', models.IntegerField()),
                ('josik', models.BooleanField()),
                ('swimming_pool', models.BooleanField()),
                ('lounge', models.BooleanField()),
                ('creditCatd', models.TextField()),
                ('peopleNum', models.IntegerField()),
                ('customers', models.ManyToManyField(blank=True, related_name='reservations', to='reservations.Customer')),
            ],
        ),
    ]
