# Generated by Django 2.2.6 on 2019-10-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
                ('package', models.IntegerField(blank=True)),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('length', models.IntegerField(blank=True)),
                ('diameter', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('feature', models.TextField(blank=True)),
                ('construction', models.TextField(blank=True)),
                ('safty', models.TextField(blank=True)),
                ('care', models.TextField(blank=True)),
                ('designer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('material', models.TextField()),
                ('environment', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='')),
                ('basket_users', models.ManyToManyField(blank=True, related_name='basket_products', to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(choices=[(1, '좋지 않음'), (2, '보통'), (3, '평균'), (4, '좋음'), (5, '매우 좋음')])),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('recommend', models.IntegerField(blank=True, choices=[(1, '예'), (2, '아니오')])),
                ('value_for_money', models.IntegerField(blank=True, choices=[(1, '좋지 않음'), (2, '보통'), (3, '평균'), (4, '좋음'), (5, '매우 좋음')])),
                ('quality', models.IntegerField(blank=True, choices=[(1, '좋지 않음'), (2, '보통'), (3, '평균'), (4, '좋음'), (5, '매우 좋음')])),
                ('design', models.IntegerField(blank=True, choices=[(1, '좋지 않음'), (2, '보통'), (3, '평균'), (4, '좋음'), (5, '매우 좋음')])),
                ('furnish', models.IntegerField(blank=True, choices=[(1, '좋지 않음'), (2, '보통'), (3, '평균'), (4, '좋음'), (5, '매우 좋음')])),
                ('function', models.IntegerField(blank=True, choices=[(1, '좋지 않음'), (2, '보통'), (3, '평균'), (4, '좋음'), (5, '매우 좋음')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('reference_users', models.ManyToManyField(blank=True, related_name='reference_comments', to=settings.AUTH_USER_MODEL)),
                ('unreference_users', models.ManyToManyField(blank=True, related_name='unreference_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
